<a href="https://colab.research.google.com/github/TaniaCruz2023/Taller-regresi-n-lineal---Tania-Cruz/blob/main/Taller_regresi%C3%B3n_lineal_Tania_Yisella_Cruz_Parada_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO 


In [ ]:
pip install wooldridge


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 25.2 MB/s eta 0:00:00


In [ ]:
import numpy as np


In [ ]:
import pandas as pd

In [ ]:
import wooldridge as wd

In [ ]:
wage = wd.data('wage1')[['wage','educ','exper']]
wage

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [ ]:
y = wage['wage'].to_numpy()
y
x = wage[['educ','exper']].to_numpy()
x

array([[11,  2],
       [12, 22],
       [11,  2],
       ...,
       [15, 13],
       [16,  5],
       [14,  5]])

In [ ]:
x = np.c_[np.ones(len(x)),x]
x

array([[ 1., 11.,  2.],
       [ 1., 12., 22.],
       [ 1., 11.,  2.],
       ...,
       [ 1., 15., 13.],
       [ 1., 16.,  5.],
       [ 1., 14.,  5.]])

BETAS

In [ ]:
betas=np.linalg.inv(x.T.dot(x)).dot(x.T.dot(y))
betas

array([-3.39053946,  0.64427208,  0.0700954 ])

y ESTIMADO

In [ ]:
y_estimado=x.dot(betas)


ERROR ESTANDAR


In [ ]:
u_estimado=y-y_estimado

PARA EXTRAER n y k

In [ ]:
n,k=x.shape
n,k

(526, 3)

DESVIACIÓN ESTANDAR

In [ ]:
sigma=sum(u_estimado**2)/(n-k)


In [ ]:
x.T

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [11., 12., 11., ..., 15., 16., 14.],
       [ 2., 22.,  2., ..., 13.,  5.,  5.]])

In [ ]:
x.T.dot(x)

array([[   526.,   6608.,   8951.],
       [  6608.,  87040., 106539.],
       [  8951., 106539., 249027.]])

Errores estandar

In [ ]:
ee=np.diag(np.sqrt(np.linalg.inv(x.T.dot(x))*sigma))
ee

<ipython-input-63-e0b44b2bf56c>:1: RuntimeWarning: invalid value encountered in sqrt
  ee=np.diag(np.sqrt(np.linalg.inv(x.T.dot(x))*sigma))


array([0.76656609, 0.05380607, 0.01097764])

**VALORES DE T**

In [ ]:
t=betas/ee
t

array([-4.423023  , 11.97396614,  6.38529107])

**INTERVALOS DE** **CONFIANZA**

Limite superior

In [ ]:
betas + (1.96*ee)


array([-1.88806992,  0.74973198,  0.09161156])

Limite inferior

In [ ]:
betas - (1.96*ee)

array([-4.89300901,  0.53881218,  0.04857923])



*   **Const:** Es estadisticamente significativo ya que no contiene la hipotesis nula dentro del intervalo
*   **Educ:** Es estadisticamente significativo ya que no contiene la hipotesis nula dentro del intervalo
*  **Exper**: Es estadisticamente significativo ya que no contiene la hipotesis nula dentro del intervalo 






In [ ]:
res=pd.dataframe({'betas':betas,'ee':ee,'t':t,
                  })